//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELepostre.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePedido
    {
        public decimal id { get; set; }
        public decimal Idpedido { get; set; }
        public Nullable<System.DateTime> horarealizada { get; set; }
        public decimal Idproducto { get; set; }
        public string EspedidoEspecial { get; set; }
        public string DescripcionEspecial { get; set; }
        public Nullable<decimal> Precio { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
