//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELepostre.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido()
        {
            this.DetallePedidoes = new HashSet<DetallePedido>();
        }
    
        public decimal Id { get; set; }
        public decimal IdUsuario { get; set; }
        public decimal IdTipo { get; set; }
        public string Direccion { get; set; }
        public string Descripcion { get; set; }
        public decimal IdTipoPago { get; set; }
        public decimal monto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePedido> DetallePedidoes { get; set; }
        public virtual TipoPago TipoPago { get; set; }
        public virtual TipoPedido TipoPedido { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
