//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELepostre.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public decimal Id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string DPI { get; set; }
        public string Email { get; set; }
        public string Direccion1 { get; set; }
        public string Direccion2 { get; set; }
        public string Status { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
